name: calendarit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localization: ^0.3.3
  go_router: ^16.0.0
  bloc: ^9.0.0
  firebase_auth: ^5.6.1
  flutter_bloc: ^9.1.1
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  flutter_appauth: ^9.0.1
  googleapis: ^14.0.0
  cloud_functions: ^5.6.1
  image_picker: ^0.8.7+4
  vertical_card_pager: ^1.5.0
  syncfusion_flutter_calendar: ^28.1.38
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.2
  googleapis_auth: ^2.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
flutter_intl:
  enabled: true

dependency_overrides:
  intl: any