// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '[REDACTED_GOOGLE_API_KEY]',
    appId: '1:291994231151:web:2011f9d7aca5b5dbd3089a',
    messagingSenderId: '291994231151',
    projectId: 'calendar-it-31e1c',
    authDomain: 'calendar-it-31e1c.firebaseapp.com',
    databaseURL: 'https://calendar-it-31e1c-default-rtdb.firebaseio.com',
    storageBucket: 'calendar-it-31e1c.firebasestorage.app',
    measurementId: 'G-HJWH0Y4JNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '[REDACTED_GOOGLE_API_KEY]',
    appId: '1:291994231151:android:bbff3f20d1d1db8ed3089a',
    messagingSenderId: '291994231151',
    projectId: 'calendar-it-31e1c',
    databaseURL: 'https://calendar-it-31e1c-default-rtdb.firebaseio.com',
    storageBucket: 'calendar-it-31e1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '[REDACTED_GOOGLE_API_KEY]',
    appId: '1:291994231151:ios:3dc53150e94a5ef6d3089a',
    messagingSenderId: '291994231151',
    projectId: 'calendar-it-31e1c',
    databaseURL: 'https://calendar-it-31e1c-default-rtdb.firebaseio.com',
    storageBucket: 'calendar-it-31e1c.firebasestorage.app',
    iosBundleId: 'com.calendarit.calendarit',
  );
}
